# This is a  workflow to build simple Node.js rpm package
# created by AlexK

name: Build-simple-RPM-package 

# Controls when the action will run. Triggers the workflow on push 
# events but only for the main branch
on:
  push:
    branches: [ main ]

# Describe workflow (made up of one or more jobs that can run sequentially or in parallel)
jobs:
           
  build-package:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so that job can access it
      - name: list-files
        run: |
          pwd
          ls -al .
          echo "========= listing of /home/runner/"
          ls -al /home/runner/
      
      # Clone the repository
      - name: Check-out the repository
        uses: actions/checkout@v2

      - name: setup-tree
        #run: mkdir -p /home/runner/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS,tmp}
        run: mkdir -p `pwd`/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS,tmp}
        
      - name: copy-source-file
        run: |
          cp nodejs-webserver-1-1.4.2.tgz `pwd`/rpmbuild/SOURCES/
          cp nodejs-webserver.spec `pwd`/rpmbuild/SPECS/

      - name: List files
        run: find ~ -name ".rpmmacros"

      # Runs a set of commands using the runners shell
      - name: Build package based on SPEC file
        run: |
          rpmbuild --version

          ##cd /home/runner/work/RPM-build-package/RPM-build-package
          rpmbuild -ba --macros=`pwd`/.rpmmacros `pwd`/rpmbuild/SPECS/nodejs-webserver.spec
