# This is a  workflow to build simple Node.js rpm package
# created by AlexK

name: Build-simple-RPM-package 

# Controls when the action will run. Triggers the workflow on push 
# events but only for the main branch
on:
  push:
    branches: [ main ]

# Describe workflow (made up of one or more jobs that can run sequentially or in parallel)
jobs:
           
  build-package:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Clone the repository
      - name: Check-out the repository
        uses: actions/checkout@v2

      - name: setup-tree
        run: mkdir -p /home/runner/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        
      - name: copy-source-file
        run: |
          cp nodejs-webserver-1-1.4.2.tgz /home/runner/rpmbuild/SOURCES/
          cp nodejs-webserver.spec /home/runner/rpmbuild/SPECS/

      # Runs a set of commands using the runners shell
      - name: Build package based on SPEC file
        run: |
          rpmbuild --version

          ##cd /home/runner/work/RPM-build-package/RPM-build-package
          rpmbuild -ba  /home/runner/rpmbuild/SPECS/nodejs-webserver.spec
       
      - name: upload-package
        uses: actions/upload-artifact@v2
        with:
          name: packaged-file
          path: /home/runner/rpmbuild/RPMS/x86_64/nodejs-webserver-1-1.4.2-1.x86_64.rpm
